import "./globals.css";
import type { Metadata } from "next";
import { M_PLUS_Code_Latin, Mulish } from "next/font/google";

const mPlusCode = M_PLUS_Code_Latin({
  subsets: ["latin"],
  variable: "--font-body",
});
const mulish = Mulish({ subsets: ["latin"], variable: "--font-heading" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mPlusCode.variable} ${mulish.variable}`}>
        {children}
      </body>
    </html>
  );
}
